import WebGLConstant from "./WebGLConstant";

enum BlendFunction {
  ZERO = WebGLConstant.ZERO,
  ONE = WebGLConstant.ONE,
  SOURCE_COLOR = WebGLConstant.SRC_COLOR,
  ONE_MINUS_SOURCE_COLOR = WebGLConstant.ONE_MINUS_SRC_COLOR,
  DESTINATION_COLOR = WebGLConstant.DST_COLOR,
  ONE_MINUS_DESTINATION_COLOR = WebGLConstant.ONE_MINUS_DST_COLOR,
  SOURCE_ALPHA = WebGLConstant.SRC_ALPHA,
  ONE_MINUS_SOURCE_ALPHA = WebGLConstant.ONE_MINUS_SRC_ALPHA,
  DESTINATION_ALPHA = WebGLConstant.DST_ALPHA,
  ONE_MINUS_DESTINATION_ALPHA = WebGLConstant.ONE_MINUS_DST_ALPHA,
  CONSTANT_COLOR = WebGLConstant.CONSTANT_COLOR,
  ONE_MINUS_CONSTANT_COLOR = WebGLConstant.ONE_MINUS_CONSTANT_COLOR,
  CONSTANT_ALPHA = WebGLConstant.CONSTANT_ALPHA,
  ONE_MINUS_CONSTANT_ALPHA = WebGLConstant.ONE_MINUS_CONSTANT_ALPHA,
  SOURCE_ALPHA_SATURATE = WebGLConstant.SRC_ALPHA_SATURATE,
}

export default BlendFunction;
