import WebGLConstants from "./WebGLConstants";

enum BlendFunction {
  ZERO = WebGLConstants.ZERO,
  ONE = WebGLConstants.ONE,
  SOURCE_COLOR = WebGLConstants.SRC_COLOR,
  ONE_MINUS_SOURCE_COLOR = WebGLConstants.ONE_MINUS_SRC_COLOR,
  DESTINATION_COLOR = WebGLConstants.DST_COLOR,
  ONE_MINUS_DESTINATION_COLOR = WebGLConstants.ONE_MINUS_DST_COLOR,
  SOURCE_ALPHA = WebGLConstants.SRC_ALPHA,
  ONE_MINUS_SOURCE_ALPHA = WebGLConstants.ONE_MINUS_SRC_ALPHA,
  DESTINATION_ALPHA = WebGLConstants.DST_ALPHA,
  ONE_MINUS_DESTINATION_ALPHA = WebGLConstants.ONE_MINUS_DST_ALPHA,
  CONSTANT_COLOR = WebGLConstants.CONSTANT_COLOR,
  ONE_MINUS_CONSTANT_COLOR = WebGLConstants.ONE_MINUS_CONSTANT_COLOR,
  CONSTANT_ALPHA = WebGLConstants.CONSTANT_ALPHA,
  ONE_MINUS_CONSTANT_ALPHA = WebGLConstants.ONE_MINUS_CONSTANT_ALPHA,
  SOURCE_ALPHA_SATURATE = WebGLConstants.SRC_ALPHA_SATURATE,
}

export default BlendFunction;
