import WebGLConstants from "./WebGLConstants";

/**
 * @public
 */
enum PixelFormat {
  RGBA = WebGLConstants.RGBA,
  RGB = WebGLConstants.RGB,
  RG = WebGLConstants.RG,
  R = WebGLConstants.RED,
  ALPHA = WebGLConstants.ALPHA,
  LUMINANCE = WebGLConstants.LUMINANCE,
  LUMINANCE_ALPHA = WebGLConstants.LUMINANCE_ALPHA,
  DEPTH_COMPONENT = WebGLConstants.DEPTH_COMPONENT,
  DEPTH_STENCIL = WebGLConstants.DEPTH_STENCIL,

  RGB_DXT1 = WebGLConstants.COMPRESSED_RGB_S3TC_DXT1_EXT,
  RGBA_DXT1 = WebGLConstants.COMPRESSED_RGBA_S3TC_DXT1_EXT,
  RGBA_DXT3 = WebGLConstants.COMPRESSED_RGBA_S3TC_DXT3_EXT,
  RGBA_DXT5 = WebGLConstants.COMPRESSED_RGBA_S3TC_DXT5_EXT,

  RGB_PVRTC_4BPPV1 = WebGLConstants.COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
  RGB_PVRTC_2BPPV1 = WebGLConstants.COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
  RGBA_PVRTC_4BPPV1 = WebGLConstants.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
  RGBA_PVRTC_2BPPV1 = WebGLConstants.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,

  RGBA_ASTC = WebGLConstants.COMPRESSED_RGBA_ASTC_4x4_WEBGL,

  RGB_ETC1 = WebGLConstants.COMPRESSED_RGB_ETC1_WEBGL,
  RGB8_ETC2 = WebGLConstants.COMPRESSED_RGB8_ETC2,           // WebGL2
  RGBA8_ETC2_EAC = WebGLConstants.COMPRESSED_RGBA8_ETC2_EAC, // WebGL2

  RGBA_BC7 = WebGLConstants.COMPRESSED_RGBA_BPTC_UNORM,
}

export default PixelFormat;
