name: Release

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm/yarn/pnpm install
        uses: Jaid/action-npm-install@v1.2.4
      - run: npm ci
      - name: Build library
        run: npm run build
      - name: pack into zip
        run: zip -r ToyGL.zip . -x "node_modules/*"
      - name: version
        run: echo "::set-output name=version::$(node -e "console.log(require('./package.json').version)")"
        id: version
      - name: Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./ToyGL.zip
          asset_name: ToyGL-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
